### ISSUE TITLE
Refactor for v0.1 

### ISSUE THREAD

**Issue by nozavroni** [nozavroni/collections#47]
Because my most recent changes have addressed so many different issues, I'm creating this issue to have a single issue number to reference and tie all the changes to. This feature branch I'm creating will address the following issues: 

- [x] #20 - indexOf()
- [ ] #21 - Add partition method
- [x] #23 - Add Arrayable support
- [x] #29 - Add random method 
- [ ] #30 - Pilfer Laravel collections methods 
- [ ] #31 - Add method similar to Laravel's getArrayableItems
- [x] #37 - Refactor collection type assertions
- [x] #38 - Get rid of CharCollection
- [x] #39 - Add collection interface 
- [x] #42 - Namespaced helper functions 
- [x] #45 - Rename getValueAtPosition and getKeyAtPosition
- [ ] #50 - Narrow down collection types
